# ????????? ??????????? ? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Freedob_Bank
spring.datasource.username=postgres
spring.datasource.password=00000

# ????????? Hibernate (JPA)
# validate ????????, ??? Spring ?????? ???????? ???????????? ?????? ? ?? ? Java-???????
spring.jpa.hibernate.ddl-auto=update

# ?????????? SQL-??????? ? ??????? (?????? ??? ???????)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ??????? ??? ?????????? ?????? ? ????????? PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect